
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  
  config.vm.network "forwarded_port", guest: 80, host: 8888, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 443, host: 8443, host_ip: "127.0.0.1"
  
  config.vm.provision "file", source: "nginx/index.html", destination: "/tmp/index.html"
  
  config.vm.provision "shell", inline: <<-SHELL
     yum install -y httpd mod_ssl
     openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -subj "/C=UA/CN=localhost/L=Lviv/O=BOG" -keyout /etc/pki/tls/private/localhost.key -out /etc/pki/tls/certs/localhost.crt
     mv /tmp/index.html /var/www/html/
     systemctl start httpd
     systemctl enable httpd
   SHELL
end
