
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "file", source: "demon/test.service", destination: "/tmp/test.service"
  config.vm.provision "shell", inline: <<-SHELL
     mkdir /var/folder{1,2}
     cat /tmp/test.service > /etc/systemd/system/test.service
     chmod +x /etc/systemd/system/test.service
     systemctl daemon-reload
     systemctl start test.service
     systemctl enable test.service
     cd /etc/cron.d
     echo '* * * * 1-5 root w>>/var/log/logged-in.log' > mycron
   SHELL
end
